# Generated by Django 4.1.5 on 2023-02-12 08:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_data', '0003_rename_certificate_education_school_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateTimeField(default=datetime.date.today, null=True)),
                ('end_date', models.DateTimeField(default=datetime.date.today, null=True)),
                ('description', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
