# Generated by Django 4.1.5 on 2023-02-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0007_alter_education_end_date_alter_education_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='certificate',
        ),
    ]
