# Generated by Django 4.1.5 on 2023-03-03 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0008_remove_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.CharField(default=uuid.UUID('71aedca1-9cd2-42a6-a962-b8989a852930'), editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=uuid.UUID('d6baf850-d3af-4db2-91fe-d17c25e6964f'), editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.CharField(default=uuid.UUID('dc7dea49-f1ef-4aa1-91c3-aae96f2264a7'), editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
